name: grimoire
services:
  tor:
    image: nausicaea/grimoire-tor:latest
    build:
      context: tor
      args:
        TOR_INTERNAL_ALIAS: tor-internal.docker
        TOR_SOCKS_PORT: 9050
    networks:
      outside: {}
      internal:
        aliases:
          - tor-internal.docker

  mitmproxy:
    image: nausicaea/grimoire-mitmproxy:latest
    build:
      context: mitmproxy
    volumes:
      - mitmproxy-data:/data
    networks:
      internal: {}

volumes:
  mitmproxy-data:
    external: true
    
networks:
  outside:
    driver: bridge

  internal:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.16.1.0/24
