name: grimoire
services:
  tor:
    image: nausicaea/tor:latest
    build:
      context: tor
      args:
        TOR_INTERNAL_ALIAS: tor-internal.docker
        TOR_SOCKS_PORT: 9050
    networks:
      outside: {}
      internal:
        aliases:
          - tor-internal.docker
    restart: always

  mitmproxy:
    image: nausicaea/mitmproxy:latest
    build:
      context: mitmproxy
    volumes:
      - mitmproxy-data:/data
    networks:
      internal: {}
    restart: always

  postgresql:
    image: docker.io/library/postgres:latest
    restart: always

  cert-recon:
    image: nausicaea/cert-recon:latest
    build:
      context: .
      args:
        ARCH: aarch64-unknown-linux-musl
        PACKAGE: cert-recon
    command: "--help"
    networks:
      outside: {}

  dns-recon:
    image: nausicaea/dns-recon:latest
    build:
      context: .
      args:
        ARCH: aarch64-unknown-linux-musl
        PACKAGE: dns-recon
    environment:
      DNS_SERVER: tor-internal.docker
    command: "--help"
    networks:
      internal: {}

  http-recon:
    image: nausicaea/http-recon:latest
    build:
      context: .
      args:
        ARCH: aarch64-unknown-linux-musl
        PACKAGE: http-recon
    environment:
      PROXY: socks5h://tor-internal.docker:9050/
    command: "--help"
    networks:
      internal: {}

volumes:
  mitmproxy-data:
    external: true
    
networks:
  outside:
    driver: bridge

  internal:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.16.1.0/24
