name: grimoire
services:
  tor:
    image: nausicaea/grimoire-tor:latest
    build:
      context: tor
      args:
        TOR_SOCKS_PORT: 9050
        TOR_SOCKS_POLICY: accept 172.28.5.0/25, accept 192.168.0.0/16
    networks:
      - outside
      - internal
    
volumes:
  tailscale-state: {}

networks:
  outside:
    driver: bridge

  internal:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.28.5.0/24
