name: grimoire
services:
  tor:
    image: nausicaea/tor:latest
    build:
      context: tor
      args:
        TOR_INTERNAL_ALIAS: tor-internal.docker
        TOR_SOCKS_PORT: 9050
    networks:
      outside: {}
      internal:
        aliases:
          - tor-internal.docker

  mitmproxy:
    image: nausicaea/mitmproxy:latest
    build:
      context: mitmproxy
    volumes:
      - mitmproxy-data:/data
    networks:
      internal: {}

  cert-recon:
    image: nausicaea/cert-recon:latest
    build:
      context: .
      args:
        PACKAGE: cert-recon
    networks:
      outside: {}

  dns-recon:
    image: nausicaea/dns-recon:latest
    build:
      context: .
      args:
        PACKAGE: dns-recon
    environment:
      DNS_SERVER: tor-internal.docker
    networks:
      internal: {}

volumes:
  mitmproxy-data:
    external: true
    
networks:
  outside:
    driver: bridge

  internal:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.16.1.0/24
