[package]
name = "grimoire"
version = "0.1.0"
edition = "2021"

[features]
strict-fqdn-validation = []

[dependencies]
regex = "1"
sqlx = { version = "0.7.4", features = ["runtime-tokio", "postgres"] }
thiserror = "1"
tracing = "0.1.40"
